# Generated by Django 5.2.6 on 2025-09-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='svnr2',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(default=''),
        ),
    ]
